# Generated by Django 3.0.2 on 2020-11-02 16:57

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=music.models.music_upload, verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
            options={
                'db_table': 'musics',
                'ordering': ('album', 'order'),
            },
        ),
    ]
