# Generated by Django 3.0.2 on 2020-11-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
