# Generated by Django 3.1.4 on 2020-12-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20201205_1316'),
        ('music', '0002_auto_20201102_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='music',
            unique_together={('album', 'order')},
        ),
    ]
