language: python

python:
  - 3.6

services:
  postgresql

addons:
  postgresql: '9.5'

install:
  - pip install -q -r requirements-dev.txt codecov

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - flake8
  - pytest music_player --nomigrations --cov=music_player

after_success:
  - codecov
