language: python

python:
  - 3.9

services: postgresql

addons:
  postgresql: "12.4"

install:
  - pip install -q -r requirements-dev.txt codecov

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - flake8
  - pytest music_player --nomigrations --cov

after_success:
  - codecov
