language: python
python:
  - 3.6
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest music_player --cov=music_player
  - python manage.py test
after_success:
  - codecov
