language: python

python:
  - 3.9

services:
  - postgresql
  - redis-server

install:
  - pip install -q -r requirements-dev.txt codecov

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - flake8
  - pytest --nomigrations --cov

after_success:
  - codecov
