# Generated by Django 3.0.2 on 2020-11-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True)),
                ('genre_image', models.ImageField(blank=True, upload_to='images/genres', verbose_name='Genre')),
            ],
            options={
                'db_table': 'genres',
                'ordering': ('description', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('band_image', models.ImageField(blank=True, upload_to='images/bands', verbose_name='Band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.Genre')),
            ],
            options={
                'db_table': 'bands',
                'ordering': ('name', 'genre'),
            },
        ),
    ]
