# Generated by Django 3.0.11 on 2020-11-09 15:13

import band.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20201102_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=models.ImageField(blank=True, upload_to=band.models.upload_band_image, verbose_name='Band'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(blank=True, upload_to=band.models.upload_genre_image, verbose_name='Genre'),
        ),
    ]
