# Generated by Django 3.0.2 on 2020-11-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('release_date', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(upload_to='images/covers', verbose_name='Cover image')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.Band')),
            ],
            options={
                'db_table': 'albums',
                'ordering': ('name', 'band', 'release_date'),
            },
        ),
    ]
