# Generated by Django 3.0.2 on 2020-11-02 20:20

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20201102_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to=album.models.upload_cover_image, verbose_name='Cover image'),
        ),
    ]
