# Generated by Django 3.1.3 on 2020-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201102_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('release_date', 'band', 'name')},
        ),
    ]
