# Generated by Django 2.0.4 on 2018-06-05 00:58

from django.db import migrations, models
import django.db.models.deletion
import music_player.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_lancamento', models.PositiveIntegerField()),
                ('capa', models.ImageField(upload_to='images/capas', verbose_name='Capa')),
            ],
            options={
                'ordering': ('nome', 'banda', 'data_lancamento'),
            },
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='images/bandas', verbose_name='Banda')),
            ],
            options={
                'ordering': ('nome', 'genero'),
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='images/generos', verbose_name='Genero')),
            ],
            options={
                'ordering': ('descricao', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('ordem', models.PositiveIntegerField(null=True)),
                ('arquivo', models.FileField(upload_to=music_player.core.models.upload_musica, verbose_name='File')),
                ('arquivo_tipo', models.CharField(blank=True, max_length=10)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Album')),
            ],
            options={
                'ordering': ('album', 'ordem'),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banda',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero'),
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Banda'),
        ),
    ]
