# Generated by Django 2.0.6 on 2018-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('email', 'nome', 'sobrenome')},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='sobre_nome',
            new_name='sobrenome',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
